spring:
  application:
    name: pastebin
  datasource:
    url: jdbc:postgresql://localhost:5433/s3_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: ZmFzZnNmc2Fmc2FkZgo=

server:
  port: 8083

s3-service:
  bucket_name: <your_bucket_name>
  access_key_id: <your_access_key_id>
  secret_key: <your_secret_key>

secret:
  key: "key12345"